name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4.1.7
        
          - name: running multiple commands
            run: |
                echo "hello"
                ls -lrta
                cat README.md

          - name: Generate ASCII artwork
            run: cowsay -f bull "Run for cover, I am a Bull..." >> bull.txt
          


             