name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4.1.7
        
          - name: welcome message
            run: echo "hello"

          - name: list files
            run: ls -lrat
          
          - name: network
            run: netstat -an

          - name: read file
            run: cat README.md

             