name: variable-secrets

on: push

env: 
    docker_user_name: katrix001
    imageName: alpine
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:

          - name: Docker Build
            run: echo docker build -t docker.io/${{env.docker_user_name}}/${{env.imageName}}:latest

          - name: Docker login
            env: 
                s3curepassword: xxxxx
            run: echo docker login --username=${{env.docker_user_name}} --password=${{env.s3curepassword}}

          - name: Docker publish
            run: echo docker push docker.io/${{env.docker_user_name}}/${{env.imageName}}:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps: 
          - name: Docker Run
            run: echo docker run -d -p 8080:80 docker.io/${{env.docker_user_name}}/${{env.imageName}}:latest