name: variable-secrets

on: push

env: 
    imageName: alpine
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:

          - name: Docker Build
            run: echo docker build -t docker.io/${{env.DOCKER_USERNAME}}/${{env.imageName}}:latest

          - name: Docker login
            env: 
                s3curepassword: xxxxx
            run: echo docker login --username=${{env.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}

          - name: Docker publish
            run: echo docker push docker.io/${{env.DOCKER_USERNAME}}/${{env.imageName}}:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps: 
          - name: Docker Run
            run: echo docker run -d -p 8080:80 docker.io/${{env.DOCKER_USERNAME}}/${{env.imageName}}:latest