name: workflow-with-multiple-jobs

on: 
  push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps: 
        - name: install cowsay in lin
          run: sudo apt install cowsay -y
          
        - name: execute cowsay command
          run: cowsay -f dragon-and-cow "ada goiyala..!" >> dragon.txt

        - name: sleep for 10 secs
          run: sleep 10
          
        - name: upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: dragon.txt

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: sleep for 10 secs
          run: sleep 10

        - name: download artifact
          uses: download-artifact@v4
          with:
            name: dragon-text-file
        
        - name: Test File Exist
          run: grep -i "dragon" dragon.txt


    
    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
        - name: download-artifact
          uses: actions/download-artifact@v4
          with: 
            name: dragon-text-file

        - name: read file
          run: cat dragon.txt

        - name: deploy
          run: echo "deploying...!"
